### ISSUE TITLE
Stackoverflow error

### ISSUE THREAD

**Issue by expez** [jonase/kibit#127]
```
Exception in thread "main" java.lang.StackOverflowError
        at clojure.core.logic$walk_STAR_.invoke(logic.clj:415)
        at clojure.core.logic$walk_STAR_$fn__1466.invoke(logic.clj:420)
        at clojure.core.logic$eval1649$fn__1650.invoke(logic.clj:1068)
        at clojure.core.logic$eval379$fn__380$G__370__387.invoke(logic.clj:85)
        at clojure.core.logic$walk_STAR_.invoke(logic.clj:416)
        at clojure.core.logic$walk_STAR_$fn__1466.invoke(logic.clj:420)
        at clojure.core.logic$eval1649$fn__1650.invoke(logic.clj:1068)
        at clojure.core.logic$eval379$fn__380$G__370__387.invoke(logic.clj:85)
        at clojure.core.logic$walk_STAR_.invoke(logic.clj:416)
        at clojure.core.logic$walk_STAR_$fn__1466.invoke(logic.clj:420)
        at clojure.core.logic$eval1649$fn__1650.invoke(logic.clj:1068)
        at clojure.core.logic$eval379$fn__380$G__370__387.invoke(logic.clj:85)
```

and on and on and on and on that stacktrace goes.

I ran `lein kibit some-file` and managed to track it down to this horrid form:

```clj
(->> (find-nodes [top-level-form-ast] #(and (#{:local :binding} (:op %)) (= local-var-name (-> % :name)) (:local %)))
       (map #(conj (vec (take 4 %)) var-name (.getCanonicalPath (java.io.File. file)) (match ns-string (first %) (second %)))))
```

**Comment by danielcompton** [comment]
Thanks for reporting this. It looks like the same issue as #78.
